# Project-wide Gradle settings.
# For more details on how to configure your build environment, visit:
# https://docs.gradle.org/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC

# Enable AndroidX and non-transitive R classes
android.useAndroidX=true
android.nonTransitiveRClass=true

# Speed up build compilation
org.gradle.caching=true
org.gradle.parallel=true
kapt.incremental.apt=true
